export const users = [
  {
    name: 'Main Admin',
    email: 'admin@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'admin',
  },
  {
    name: 'Electronics Seller',
    email: 'electronics@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'electronics',
  },
  {
    name: 'Solar Energy Seller',
    email: 'solar@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'solar',
  },
  {
    name: 'Fashion & Beauty Seller',
    email: 'fashion@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'fashion',
  },
  {
    name: 'Groceries Seller',
    email: 'groceries@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'groceries',
  },
  {
    name: 'Home Appliances Seller',
    email: 'appliances@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'appliances',
  },
  {
    name: 'Vehicles Seller',
    email: 'vehicles@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'vehicles',
  },
  {
    name: 'Crafts & Handmade Seller',
    email: 'crafts@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'crafts',
  },
  {
    name: 'Farm & Food Seller',
    email: 'farm@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'farm',
  },
  {
    name: 'Charcoal & Fuel Seller',
    email: 'fuel@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'fuel',
  },
  {
    name: 'Other/Misc Seller',
    email: 'other@example.com',
    password: 'password123',
    isAdmin: true,
    sellerType: 'other',
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    isAdmin: false,
    sellerType: 'customer',
  },
];